### ISSUE TITLE
dropped game

### ISSUE THREAD

**Issue by PapaSpiff** [tkgstrator/Salmonia#14]
Here is a small log:

20:51:33 Result 21528 downloading
20:51:35 21528 -> 1412876 uploading
21:00:10 Result 21529 downloading
21:01:11 Iksm Session regenarating
21:01:11 Getting Access Token
21:01:12 Getting Splatoon Token
21:01:16 Getting Splatoon Access Token
21:01:22 Getting Iksm Session
21:02:23 Waiting New Results
21:09:33 Result 21530 downloading
21:09:34 21530 -> 1412909 uploading

So 21529 was downloaded, but then an error occured. Once the session has been regenerated, only the next game is processed.
I am currently testing a potential fix for it.

**Comment by ylafon** [comment]
Fixed by c04ead03028a4dae3fc6fcad18df01cbbffea078
